### ISSUE TITLE
What version of WDDM is this?

### ISSUE THREAD

**Issue by BelleNottelling** [woachk/rpigpu#1]
From what I hear it needs to be WDDM 2.0 for the task manager to show the usage, which I think was a goal for these drivers

**Comment by BelleNottelling** [comment]
Well, I'm stupid. Just looked in dxdiag

**Comment by woachk** [comment]
WDDM 1.3 for now

**Comment by BelleNottelling** [comment]
Thanks for answering, I ended up realizing that later on lol. 

Are you planning on updating it to 2.0? From what I can tell, there are two ways to get the GPU to render games and such, as most things won't use it as a render device due to it being reported as having no display attached

1: write a display driver, this would allow windows to correctly understand that it is indeed hooked up to a display, and then applications will render off of it t

2: update these drivers to WDDM 2.0 and that add it support for Microsoft graphics hybrid so it will know how to render video on the GPU and then display it through the Microsoft basic display adapter (much like how people play games on old mining graphics cards with no video out)
